services:
  - type: web
    name: schedula-api-artisans
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: schedula-db
          property: connectionString
      - key: RENDER
        value: 'true'
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: FRONTEND_URL
        value: https://your-frontend-url.com
    healthCheckPath: /api/hello

databases:
  - name: schedula-db
    plan: free
